security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        admin:
            pattern:  /administrator(.*)
            form_login:
               provider:   fos_userbundle
               login_path: /administrator/login
               check_path:     /administrator/login_check
               default_target_path: /administrator/dashboard
            logout:
               path:           /administrator/logout
               target:         /administrator/login
            anonymous:  true

    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/administrator/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator/, role: ROLE_ADMIN }
